# Generated by Django 4.2 on 2023-06-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentGrade',
            new_name='GradeStudent',
        ),
    ]
